### ISSUE TITLE
Unit test failing when column type is json

### ISSUE THREAD

**Issue by fernandoiwamoto** [ankane/lockbox#39]
I got error on my unit test when trying to save a model with column type is json in my Company model:
` 
Company.create(metadata: { content: "something" })
`

`encrypts :metadata, type: :json`

` 
NoMethodError:
       undefined method `metadata_ciphertext=' for #<Company:0x000055fbe0727ce8>
       Did you mean?  metadata_change
`

And this points me to:
https://github.com/ankane/lockbox/blob/v0.3.3/lib/lockbox/model.rb#L213

When using another model with column type string, it works fine.

**Comment by ankane** [comment]
Hey @fernandoiwamoto, make sure your model has a `metadata_ciphertext` field with type `text`.

```rb
add_column :companies, :metadata_ciphertext, :text
```

**Comment by fernandoiwamoto** [comment]
yup, I had this too, but after I updated the gem to 0.3.4 it worked fine.

**Comment by ankane** [comment]
I'm not sure anything around this was changed between those versions, but glad it's working.
