### ISSUE TITLE
undefined method `synchronize' for nil:NilClass

### ISSUE THREAD

**Issue by stevenou** [ankane/lockbox#147]
My project updated from 0.6.6 to 0.6.7 and I am now getting this error where `encrypts` gets called (which means the entire test suite fails as the models won't load):

```
undefined method `synchronize' for nil:NilClass
```

I am on Rails 6.1.4.4 and Ruby 3.0.2.

I've been trying to replicate the issue in a clean project but not having luck. I know that's key to troubleshooting, but there is also something relatively unique about my setup that might give you some ideas of what the issue could be:

I have abstract models set up like so:
```
class UserBase < ApplicationRecord
  self.abstract_class = true

  class << self
    def inherited(subclass)
      subclass.encrypts :token

      super
    end
  end
end
```
And then the actual model inherits:
```
class User < UserBase
end
```

So the whole `inherited` thing was working fine on version 0.6.6 but giving me trouble on 0.6.7. 

I'm going to keep investigating and seeing if I can cleanly reproduce the issue. In the mean time, I'd appreciate any insights you might have. Thanks!

**Comment by ankane** [comment]
Hey @stevenou, can you paste the full stack trace?

**Comment by stevenou** [comment]
@ankane ah yes, I was trying to figure out how to get the full stack trace. Here it is:

```
NoMethodError:
  undefined method `synchronize' for nil:NilClass
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.4/lib/active_record/model_schema.rb:536:in `load_schema'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.4/lib/active_record/model_schema.rb:460:in `_default_attributes'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/lockbox-0.6.7/lib/lockbox/model.rb:324:in `block (2 levels) in lockbox_encrypts'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/lockbox-0.6.7/lib/lockbox/model.rb:58:in `class_eval'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/lockbox-0.6.7/lib/lockbox/model.rb:58:in `block in lockbox_encrypts'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/lockbox-0.6.7/lib/lockbox/model.rb:37:in `each'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/lockbox-0.6.7/lib/lockbox/model.rb:37:in `lockbox_encrypts'
# ./app/models/shipped_base/storefront.rb:11:in `inherited'
# ./app/models/storefront.rb:3:in `<top (required)>'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
# ./spec/models/storefront_spec.rb:3:in `<top (required)>'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2112:in `load'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2112:in `load_file_handling_errors'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1615:in `block in load_spec_files'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1613:in `each'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1613:in `load_spec_files'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:102:in `setup'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:86:in `run'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
# /Users/stevenou/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
# /Users/stevenou/.rbenv/versions/3.0.2/bin/rspec:23:in `load'
# /Users/stevenou/.rbenv/versions/3.0.2/bin/rspec:23:in `<main>'
```

**Comment by ankane** [comment]
Looks like it's due to the new warning for default attributes. Does moving `super` before `subclass.encrypts :token` fix it?

**Comment by stevenou** [comment]
@ankane that does appear to fix it!

**Comment by ankane** [comment]
Just pushed a new release that should fix it (0.6.8). The default attribute check was causing the model schema to load early.

I'd still recommend calling `super` first to make sure Active Record components are loaded before `encrypts` is called.

Thanks for reporting!
